import { test, expect } from '@playwright/test';
import { runAxe } from './axe.setup';

/**
 * a11y miniapp-home — Phase 4 Plan 4-08 (EXIT GATE).
 *
 * Targets the dogfood route at /preview/miniapp-home (NOT /preview/[item]/miniapp-home).
 * The dogfood route is a static page generated by next build; no manifest+barrel
 * deferral applies here — this URL is reachable as soon as Phase 4 ships.
 */

test.describe('a11y miniapp-home', () => {
  test('a11y miniapp-home (light)', async ({ page }) => {
    await page.goto('/preview/miniapp-home');
    await page.waitForLoadState('networkidle');
    const results = await runAxe(page);
    expect(results.violations).toEqual([]);
  });

  test('a11y miniapp-home (dark)', async ({ page }) => {
    await page.goto('/preview/miniapp-home');
    await page.evaluate(() => document.documentElement.classList.add('dark'));
    await page.waitForLoadState('networkidle');
    const results = await runAxe(page);
    expect(results.violations).toEqual([]);
  });
});
